"""Regenerate DeltaTestVectors.hpp from the Python reference implementation.

Copyright (c) 2026 Michael Starch

    python generate_vectors.py > DeltaTestVectors.hpp

The flight decoders are then checked against these ground-produced patches in DeltaTestMain.cpp.
"""

import random
from importlib.metadata import version as _pkg_version

from fprime_extras_spatch import coders, spatch

CHUNK_BYTES = 300  # below the buffer sizes so every chunk crosses buffer boundaries; many chunks per image


def make_images():
    rng = random.Random(0x5A17)
    old = bytearray(rng.getrandbits(8) for _ in range(2000))
    # Add a compressible region so LZSS/RLE have something to do
    old[400:600] = b"\x00" * 200
    old[600:800] = bytes(range(50)) * 4
    new = bytearray(old)
    for i in range(0, len(new), 97):
        new[i] = (new[i] + 3) & 0xFF
    new[1000:1000] = b"INSERT" * 20  # insertion
    del new[1500:1550]  # deletion
    new.extend(b"\xaa" * 130)  # tail growth
    return bytes(old), bytes(new)


def emit_array(name, data):
    print(f"static const U8 {name}[] = {{")
    for i in range(0, len(data), 16):
        print("    " + ", ".join(f"0x{b:02X}" for b in data[i : i + 16]) + ",")
    if not data:
        print("    0x00,  // placeholder for empty array")
    print("};")
    print(f"static const FwSizeType {name}_SIZE = {len(data)};\n")


def main():
    old, new = make_images()
    print("// Generated by generate_vectors.py -- do not edit by hand")
    print(f"// Matcher: bsdiff4 {_pkg_version('bsdiff4')}; SPatch v{spatch.VERSION}")
    print("// Copyright (c) 2026 Michael Starch")
    print("#ifndef Update_Delta_DeltaTestVectors_HPP")
    print("#define Update_Delta_DeltaTestVectors_HPP")
    print('#include "Fw/FPrimeBasicTypes.hpp"')
    print("namespace Update {\nnamespace TestVectors {\n")
    print(f"static const U32 CHUNK_BYTES = {CHUNK_BYTES};")
    print(f"static const U32 OLD_CRC = 0x{spatch.crc32(old):08X}u;")
    print(f"static const U32 NEW_CRC = 0x{spatch.crc32(new):08X}u;\n")
    emit_array("OLD_IMAGE", old)
    emit_array("NEW_IMAGE", new)
    for name, cid in coders.NAMES.items():
        emit_array(f"PATCH_{name.upper()}", spatch.create(old, new, cid, CHUNK_BYTES))
    # Standalone coder vectors: raw -> coded
    raw = bytes(range(256)) + b"\x00" * 300 + b"abcabcabcabcabcabd" * 10 + old[:500]
    emit_array("CODER_RAW", raw)
    for name, cid in coders.NAMES.items():
        emit_array(f"CODER_{name.upper()}", coders.ENCODERS[cid](raw))
    print("}  // namespace TestVectors\n}  // namespace Update\n#endif")


if __name__ == "__main__":
    main()
